name: run-tests

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                php: [8.0, 8.1, 8.2, 8.3]
                laravel: [^8.80, 9.*, 10.*, 11.*]
                dependency-version: [prefer-lowest, prefer-stable]
                exclude:
                    -   laravel: 11.*
                        php: 8.0
                    -   laravel: 11.*
                        php: 8.1
                    -   laravel: 10.*
                        php: 8.0
                    -   laravel: ^8.80
                        php: 8.2
                    -   laravel: ^8.80
                        php: 8.3

        runs-on: ubuntu-latest
        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "illuminate/contracts:${{ matrix.laravel }}" --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist  --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit
